[project]
name = "contentflow"
version = "0.1.0"
requires-python = ">=3.12"
description = "ContentFlow monorepo backend"
readme = "README.md"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
